### ISSUE TITLE
Bokeh plotting issue

### ISSUE THREAD

**Issue by eslrgs** [MARDAScience/SediNet#5] opened 2019-11-20 07:25 UTC
Hi,

I am having an error running a custom config. The error results in a '500: Internal Server Error' when I run the final Jupyter Cell in the RunSediNetGlobal notebook. I have been trying to solve it, but the only potential error I can see is that the webpage 'https://www.allaboutbirds.org/guide/assets/photo/{n}-1280px.jpg' is down. Could this be the issue?

When I run the script in terminal I receive the attached error, which I presume is related.

![Screen Shot 2019-11-20 at 07 23 45](https://user-images.githubusercontent.com/33627729/69217555-d79a3a00-0b66-11ea-9cf4-70705bafbbd6.png)

Thank you for developing this great tool!

**Comment by dbuscombe-usgs** [comment] 2019-11-20 16:05
I can take a look at this later, but for now, does it work if you replace that placeholder image (that it needs to initialize) with another web image. Say, 
```
img = https://mardascience.com/wp-content/uploads/2019/07/cv-1024x768.png
```
?
If not, I'll address later

**Comment by eslrgs** [comment] 2019-11-20 16:16
When using this img I get the following error:

![Screen Shot 2019-11-20 at 16 13 37](https://user-images.githubusercontent.com/33627729/69256095-d7bf2780-0bb0-11ea-819e-f753b956650a.png)

It looks as though there grainsize data has not been generated for some reason:

![Screen Shot 2019-11-20 at 16 15 19](https://user-images.githubusercontent.com/33627729/69256215-0b9a4d00-0bb1-11ea-8439-bad690ce3382.png)

**Comment by MARDAScience** [comment] 2019-11-21 00:01
I can't reproduce your error with the provided data, and the issue isn't related to the URL used to initialize the panel pane object. So, I think there is a problem with your input csv and/or configuration variables. Can you share that and your configuration settings?

**Comment by eslrgs** [comment] 2019-11-21 06:56
Yes no problem - thanks for the help.

Here they are: 

**config** 

{
  "base" : 14,
  "csvfile" : "data_annot.csv",
  "P20": "P20",
  "P60": "P60",
  "P80": "P80",
  "res_folder": "annot_model",
  "name"  : "sand_generic_3prcs",
  "dropout": 0.25,
  "add_bn": true
}

**csv:**

files | P20 | P60 | P80
-- | -- | -- | --
images/4_2_Sa.jpg |   |  
images/4_2_Sa.jpg |   |  
images/4D_1_Sa.jpg |   |  
images/4D_1_Sb.jpg |   |  
images/4D_Spinch.jpg |   |  
images/7_2_bh.jpg |   |  
images/7_3_Sa.jpg |   |  
images/8_5Shb.jpg |   |  
images/13_2_Sb.jpg |   |  
images/13_2_Sc.jpg |   |  
images/13_3_Sa.jpg |   |  
images/13_3_Sb.jpg |   |  
images/19_1_Sa.jpg |   |  
images/44_Sa.jpg |   |  
images/H1_Sb.jpg |   |  
images/H1_Sc.jpg |   |

**Comment by dbuscombe-usgs** [comment] 2019-11-21 13:30
So, you are trying to train a model without providing any input data. You are only providing files, no percentile quantities. If you want to estimate the grain size of each image, use the provided function. Closing because the issue is unrelated to the problem.

**Closed by dbuscombe-usgs** 2019-11-21 13:30 UTC

**Comment by eslrgs** [comment] 2019-11-21 13:37
Ah, I see the problem. Thanks for replying so quickly.
