### ISSUE TITLE
'tensorflow' has no attribute 'get_default_graph'

### ISSUE THREAD

**Issue by SiccarPoint** [MARDAScience/SediNet#3] opened 2019-11-04 15:46 UTC
Hi David,

Directed here from your EPSL preprint - this project looks amazing!

However, I'm up against a brick wall immediately on local install. Set up a conda env using the yml file exactly as you indicated in the instructions. However, on attempting to ` python train_sedinet_continuous.py -c config_9percentiles.json` within the env, I immediately get an AttributeError:

```
Using TensorFlow backend.
14
204 train files
205 test files
==========================================
Traceback (most recent call last):
  File "train_sedinet_continuous.py", line 53, in <module>
    run_continuous_training(vars, csvfile, base, name, res_folder, dropout, add_bn)
  File "/Users/daniel/development/SediNet/sedinet_models.py", line 317, in run_continuous_training
    model = make_cont_sedinet(base, vars, add_bn, dropout)
  File "/Users/daniel/development/SediNet/sedinet_models.py", line 598, in make_cont_sedinet
    input_layer = Input(shape=(IM_HEIGHT, IM_WIDTH*2, 1))
  File "/Users/daniel/anaconda3/envs/sedinet/lib/python3.7/site-packages/keras/engine/input_layer.py", line 178, in Input
    input_tensor=tensor)
  File "/Users/daniel/anaconda3/envs/sedinet/lib/python3.7/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/Users/daniel/anaconda3/envs/sedinet/lib/python3.7/site-packages/keras/engine/input_layer.py", line 39, in __init__
    name = prefix + '_' + str(K.get_uid(prefix))
  File "/Users/daniel/anaconda3/envs/sedinet/lib/python3.7/site-packages/keras/backend/tensorflow_backend.py", line 74, in get_uid
    graph = tf.get_default_graph()
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'
```

A little nosing around on other people's error reports indicates this might be a weird interaction between `keras` and `tensorflow` v. 2.0.0, fixable by modifying the imports of these, but I don't know either well enough to follow (See e.g. https://github.com/keras-team/keras/issues/12783).

Alternatively,  I also got a working fix with a `tensorflow` version downgrade, `2.0` -> `1.14`, which I guess would be a good short term solution if enforced in your environment yaml file?

Anyhow, just a heads up that given the article just went out, you might get some confused users appearing in the near future. Definitely looks like a versioning thing to me.

---

This is a mac, but I don't think that's super relevant. In case you need it, `conda list`:
```
# packages in environment at /Users/daniel/anaconda3/envs/sedinet:
#
# Name                    Version                   Build  Channel
_tflow_select             2.3.0                       mkl  
absl-py                   0.8.0                    py37_0  
appnope                   0.1.0                    py37_0  
asn1crypto                1.2.0                    py37_0  
astor                     0.8.0                    py37_0  
attrs                     19.3.0                     py_0  
backcall                  0.1.0                    py37_0  
blas                      1.0                         mkl  
bleach                    3.1.0                    py37_0  
bokeh                     1.4.0                    pypi_0    pypi
c-ares                    1.15.0            h1de35cc_1001  
ca-certificates           2019.10.16                    0  
certifi                   2019.9.11                py37_0  
cffi                      1.13.1           py37hb5b8e2f_0  
chardet                   3.0.4                 py37_1003  
cryptography              2.8              py37ha12b0ac_0  
cycler                    0.10.0                   py37_0  
dbus                      1.13.12              h90a0687_0  
decorator                 4.4.1                      py_0  
defusedxml                0.6.0                      py_0  
django                    2.2.7                    pypi_0    pypi
entrypoints               0.3                      py37_0  
expat                     2.2.6                h0a44026_0  
freetype                  2.9.1                hb4e5f40_0  
gast                      0.2.2                    py37_0  
gettext                   0.19.8.1             h15daf44_3  
glib                      2.56.2               hd9629dc_0  
google-pasta              0.1.7                      py_0  
grpcio                    1.16.1           py37h044775b_1  
h5py                      2.9.0            py37h3134771_0  
hdf5                      1.10.4               hfa1e0ec_0  
icu                       58.2                 h4b95b61_1  
idna                      2.8                      py37_0  
image                     1.5.27                   pypi_0    pypi
importlib_metadata        0.23                     py37_0  
intel-openmp              2019.4                      233  
ipykernel                 5.1.3            py37h39e3cac_0  
ipython                   7.9.0            py37h39e3cac_0  
ipython_genutils          0.2.0                    py37_0  
ipywidgets                7.5.1                      py_0  
jedi                      0.15.1                   py37_0  
jinja2                    2.10.3                     py_0  
joblib                    0.13.2                   py37_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.1.1                    py37_0  
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.0.0                    py37_0  
jupyter_core              4.6.0                    py37_0  
keras                     2.2.4                         0  
keras-applications        1.0.8                      py_0  
keras-base                2.2.4                    py37_0  
keras-preprocessing       1.1.0                      py_1  
kiwisolver                1.1.0            py37h0a44026_0  
libcxx                    4.0.1                hcfea43d_1  
libcxxabi                 4.0.1                hcfea43d_1  
libedit                   3.1.20181209         hb402a30_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.37               ha441bb4_0  
libprotobuf               3.9.2                hd9629dc_0  
libsodium                 1.0.16               h3efe00b_0  
llvm-openmp               4.0.1                hcfea43d_1  
markdown                  3.1.1                    py37_0  
markupsafe                1.1.1            py37h1de35cc_0  
matplotlib                3.1.1            py37h54f8f79_0  
mistune                   0.8.4            py37h1de35cc_0  
mkl                       2019.4                      233  
mkl-service               2.3.0            py37hfbe908c_0  
mkl_fft                   1.0.14           py37h5e564d8_0  
mkl_random                1.1.0            py37ha771720_0  
more-itertools            7.2.0                    py37_0  
nbconvert                 5.6.0                    py37_1  
nbformat                  4.4.0                    py37_0  
ncurses                   6.1                  h0a44026_1  
notebook                  6.0.1                    py37_0  
numpy                     1.17.2           py37h99e6662_0  
numpy-base                1.17.2           py37h6575580_0  
openssl                   1.1.1d               h1de35cc_3  
opt_einsum                3.1.0                      py_0  
packaging                 19.2                     pypi_0    pypi
pandas                    0.25.2           py37h0a44026_0  
pandoc                    2.2.3.2                       0  
pandocfilters             1.4.2                    py37_1  
panel                     0.6.4                    pypi_0    pypi
param                     1.9.2                    pypi_0    pypi
parso                     0.5.1                      py_0  
pcre                      8.43                 h0a44026_0  
pexpect                   4.7.0                    py37_0  
pickleshare               0.7.5                    py37_0  
pillow                    6.2.1                    pypi_0    pypi
pip                       19.3.1                   py37_0  
prometheus_client         0.7.1                      py_0  
prompt_toolkit            2.0.10                     py_0  
protobuf                  3.9.2            py37h0a44026_0  
ptyprocess                0.6.0                    py37_0  
pycparser                 2.19                     py37_0  
pyct                      0.4.6                    pypi_0    pypi
pygments                  2.4.2                      py_0  
pyopenssl                 19.0.0                   py37_0  
pyparsing                 2.4.2                      py_0  
pyqt                      5.9.2            py37h655552a_2  
pyrsistent                0.15.4           py37h1de35cc_0  
pysocks                   1.7.1                    py37_0  
python                    3.7.5                h359304d_0  
python-dateutil           2.8.0                    py37_0  
pytz                      2019.3                     py_0  
pyviz-comms               0.7.2                    pypi_0    pypi
pyyaml                    5.1.2            py37h1de35cc_0  
pyzmq                     18.1.0           py37h0a44026_0  
qt                        5.9.7                h468cd18_1  
qtconsole                 4.5.5                      py_0  
readline                  7.0                  h1de35cc_5  
requests                  2.22.0                   py37_0  
scikit-learn              0.21.3           py37h27c97d8_0  
scipy                     1.3.1            py37h1410ff5_0  
send2trash                1.5.0                    py37_0  
setuptools                41.6.0                   py37_0  
sip                       4.19.8           py37h0a44026_0  
six                       1.12.0                   py37_0  
sqlite                    3.30.1               ha441bb4_0  
sqlparse                  0.3.0                    pypi_0    pypi
tensorboard               2.0.0              pyhb230dea_0  
tensorflow                2.0.0           mkl_py37hda344b4_0  
tensorflow-base           2.0.0           mkl_py37h66b1bf0_0  
tensorflow-estimator      2.0.0              pyh2649769_0  
termcolor                 1.1.0                    py37_1  
terminado                 0.8.2                    py37_0  
testpath                  0.4.2                    py37_0  
tk                        8.6.8                ha441bb4_0  
tornado                   6.0.3            py37h1de35cc_0  
traitlets                 4.3.3                    py37_0  
urllib3                   1.24.2                   py37_0  
wcwidth                   0.1.7                    py37_0  
webencodings              0.5.1                    py37_1  
werkzeug                  0.16.0                     py_0  
wheel                     0.33.6                   py37_0  
widgetsnbextension        3.5.1                    py37_0  
wrapt                     1.11.2           py37h1de35cc_0  
xz                        5.2.4                h1de35cc_4  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.3.1                h0a44026_3  
zipp                      0.6.0                      py_0  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by dbuscombe-usgs** [comment] 2019-11-04 15:52
Thanks, yes I developed using TF 1.14 and this release coincided almost exactly with Tensorflow 2 release, which breaks most older code. I plan to upgrade it to TF2 this week once I come up for air. Thanks for the detailed comment and the encouragement

**Comment by SiccarPoint** [comment] 2019-11-04 15:53
Classic publication timing luck! Good luck with it. I'll stick on tf=1.14 while messing about.

**Comment by MARDAScience** [comment] 2019-11-05 16:17
I just uploaded a new version tested with a fresh Tensorflow 2 install. I also switched from a keras native install to tf.keras, which is now recommended by keras. Couple of other bug fixes related to plotting. Please reinstall conda env and let me know if you have issues with the new code

**Comment by SiccarPoint** [comment] 2019-11-06 10:52
Thank you for this! Unfortunately, I'm now getting some install errors:
```
(base) ➜  SediNet git:(master) conda env create -f conda_env/sedinet.yml
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - tensorflow-gpu==2.0
```
Any ideas? conda etc up-to-date on my machine, and the install of tensorflow v.2 was fine the first time (hence the issue in the first place!)

**Comment by dbuscombe-usgs** [comment] 2019-11-06 14:41
perhaps just `tensorflow-gpu` in your case, then. Right now, it's difficult to know if TF 2 will be installed by default in different systems. On Linux, where I develop, it is not, hence the specification of the version. I suspect it might be variable dependent on conda version. Did you do a `conda update base` or `conda update anaconda` or similar on an old install, or are you using a fresh install.

I'm going to leave the yaml file as is for now, for the reasons I described earlier, but I'll add a note to the README. Thanks for helping debug this - it is especially helpful that you are on a mac, which I don't have access to

**Comment by SiccarPoint** [comment] 2019-11-06 14:49
No worries! Good to help!

I got it. On mac, there is simply no support for tensor flow-gpu it would seem. The package just doesn't exist for this: https://www.tensorflow.org/install/source#install_gpu_support_optional_linux_only

...which doesn't sound promising. I note things were working with tensorflow=1.14 before, presumably without gpu support as well, so hopefully there's a relatively simple solution lurking here?

**Comment by dbuscombe-usgs** [comment] 2019-11-06 14:56
Ah! I didn't realize no TF2 on mac. I'm sure it's coming soon. In the meantime, you could try adding this to the top of the code
```
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
```

? haven't tried it yet

**Comment by SiccarPoint** [comment] 2019-11-06 15:02
TF2 yes, TF-gpu no I think. I have a nasty feeling this might be a hardware compatibility thing.

You mean put the code at the top of e.g. `train_sedinet_continuous.py`?

**Comment by dbuscombe-usgs** [comment] 2019-11-06 15:04
You would actually put it right at the top of ```sedinet_utils.py```. Also note that the use of "GPU 0" is hard-coded in. For CPU, use -1

**Comment by SiccarPoint** [comment] 2019-11-06 15:26
That works if I modify the yaml file for the environment `tensorflow-gpu==2.0` -> `tensorflow`, but that's needed too.

I just mocked up a PR (#4) that makes everything work mac-wise. Does this also work on UNIX, or have I just killed all the gnu acceleration you carefully built in by not importing the `gpu` version?

**Comment by SiccarPoint** [comment] 2019-11-06 15:28
A viable alternative might be to maintain a separate yaml file for mac users, that only installs `tensorflow`, while leaving `tensorflow-gpu` for everyone else.

**Comment by MARDAScience** [comment] 2019-11-21 00:04
Thanks I like your latter idea of having a separate config file for mac users. I will work into the next update. Closing this issue but feel free to reopen if you have more ideas

**Closed by MARDAScience** 2019-11-21 00:04 UTC

**Comment by SiccarPoint** [comment] 2019-11-21 08:57
Cool!

**Comment by SaiCharanReddyObiliachigari** [comment] 2020-06-23 00:17
AttributeError: module 'tensorflow' has no attribute 'get_default_graph'

I am getting the above error, How to solve this
I just install NVIDIA GPU

**Comment by dbuscombe-usgs** [comment] 2020-06-29 14:25
Looking into this today. I can't reproduce the error: please let me know your OS, python, tensorflow and keras versions. Also, details about the dataset and config file. Full error message please
